version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-container
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=host.docker.internal:2345
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  jenkins_home:
